# Generated by Django 3.2.16 on 2023-01-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id_colecao', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('id_livro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id_utilizador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='utilizadores/')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id_critica', models.AutoField(primary_key=True, serialize=False)),
                ('id_livro', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('num_gostos', models.IntegerField(default=0)),
                ('classif', models.IntegerField()),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcrew.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('id_critica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcrew.critica')),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcrew.utilizador')),
            ],
        ),
    ]
