# Generated by Django 3.2.16 on 2023-01-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='categoria',
            field=models.IntegerField(default=0),
        ),
    ]
