# Generated by Django 3.2.16 on 2023-01-07 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrew', '0002_alter_colecao_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colecao',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='colecao',
            name='id_livro',
        ),
        migrations.AddField(
            model_name='colecao',
            name='idUtilizador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookcrew.utilizador'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubColecao',
            fields=[
                ('id_sub_colecao', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.IntegerField(default=0)),
                ('id_livro', models.CharField(max_length=200)),
                ('id_colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcrew.colecao')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoAmizade',
            fields=[
                ('id_pedido_amizade', models.AutoField(primary_key=True, serialize=False)),
                ('id_utilizador_env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizador_env', to='bookcrew.utilizador')),
                ('id_utilizador_recebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizador_rec', to='bookcrew.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Amizade',
            fields=[
                ('id_amizade', models.AutoField(primary_key=True, serialize=False)),
                ('id_utilizador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizade_1', to='bookcrew.utilizador')),
                ('id_utilizador_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizade_2', to='bookcrew.utilizador')),
            ],
        ),
    ]
