# Generated by Django 3.2.16 on 2023-01-07 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrew', '0003_auto_20230107_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colecao',
            name='idUtilizador',
        ),
        migrations.AddField(
            model_name='colecao',
            name='id_utilizador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookcrew.utilizador'),
            preserve_default=False,
        ),
    ]
